import os
import socket

from funciones.anydesk import obtener_anydesk
from funciones.cpu import obtener_cpu
from funciones.ip import obtener_ip
from funciones.ram import obtener_ram
from funciones.serial import obtener_serial
from funciones.sistema_operativo import obtener_sistema

# ── Rutas ──────────────────────────────────────────────────────────────────────
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH   = os.path.join(BASE_DIR, "config.txt")
RESPALDOS_DIR = os.path.join(BASE_DIR, "RESPALDOS_FALLIDOS")
ICON_PATH     = os.path.join(BASE_DIR, "assets", "iconoMuni.png")
BANNER_PATH   = os.path.join(BASE_DIR, "assets", "Bannermuni.png")

# ── Campos automáticos ────────────────────────────────────────────────────────
CAMPOS_AUTO = [
    ("nombre_pc",         socket.gethostname,   "Nombre PC"),
    ("sistema_operativo", obtener_sistema,       "Sistema operativo"),
    ("anydesk",           obtener_anydesk,       "AnyDesk"),
    ("cpu",               obtener_cpu,           "Procesador"),
    ("ram",               obtener_ram,           "RAM"),
    ("ip",                obtener_ip,            "IP"),
    ("serial",            obtener_serial,        "N° Serie"),
]

CAMPOS_MONITOR   = [("marca", "Marca:"), ("modelo", "Modelo:"), ("pulgadas", "Pulgadas:")]
CAMPOS_IMPRESORA = [("tipo", "Tipo:"), ("marca", "Marca:"), ("modelo", "Modelo:"),
                    ("ip", "IP:"), ("toner_tinta", "Tóner / Tinta:")]

OBLIGATORIOS = {
    "usuario":             "Funcionario responsable",
    "registrado_por":      "Registrado por",
    "ubicacion":           "Ubicación",
    "departamento_manual": "Departamento / dirección",
}

DEPARTAMENTOS_UBICACION = {
    "ADMINISTRACION": "Dieciocho de Septiembre 510",
    "ADM-INFORMATICA": "Dieciocho de Septiembre 510",
    "ADM-EVENTOSRECREATIVOS": "Dieciocho de Septiembre 510",
    "ADM-PSICOSOCIAL": "Dieciocho de Septiembre 510",
    "ADM-TRANSPARENCIA": "Dieciocho de Septiembre 510",
    "ADM-VIGILANTES": "Dieciocho de Septiembre 510",
    "ADM-ORGANISMO DE SEGURIDAD INTERNO": "Dieciocho de Septiembre 510",
    "CONCEJO": "Dieciocho de Septiembre 510",
    "CONTROL": "Dieciocho de Septiembre 510",
    "DAF": "Dieciocho de Septiembre 510",
    "DAF-RENTAS": "Dieciocho de Septiembre 510",
    "DAF-R.R.H.H.": "Dieciocho de Septiembre 510",
    "DAF-TESORERIA": "Dieciocho de Septiembre 510",
    "DAF-ADQUISICIONES": "Dieciocho de Septiembre 510",
    "DAF-CONTABILIDAD": "Dieciocho de Septiembre 510",
    "DAF-COBRANZAS": "Dieciocho de Septiembre 510",
    "DAF-BIENESTAR": "Dieciocho de Septiembre 510",
    "DAF-GESTION DE PAGO": "Dieciocho de Septiembre 510",
    "DAF-HONORARIOS": "Dieciocho de Septiembre 510",
    "DAF-CONVENIOS": "Dieciocho de Septiembre 510",
    "DAF-INVENTARIO": "Dieciocho de Septiembre 510",
    "DAF-PREVENCION DE RIESGO": "Dieciocho de Septiembre 510",
    "JURIDICA": "Dieciocho de Septiembre 510",
    "OFICINA DE PARTES": "Dieciocho de Septiembre 510",
    "SECRETARIA MUNICIPAL": "Dieciocho de Septiembre 510",
    "SUREFI": "Dieciocho de Septiembre 510",
    "TRANSPARENCIA EXTERNA": "Dieciocho de Septiembre 510",
    "ALCALDIA": "Dieciocho de Septiembre 510",
    "ALCALDIA-COMUNICACIONES": "Dieciocho de Septiembre 510",
    "ALCALDIA-REDES SOCIALES": "Dieciocho de Septiembre 510",
    "RELACIONES PUBLICAS": "Dieciocho de Septiembre 510",
    "PROTOCOLO": "Dieciocho de Septiembre 510",
    "GABINETE": "Dieciocho de Septiembre 510",
    "CASCHILE": "Dieciocho de Septiembre 510",
    "DIDECO": "Arauco 983",
    "DIDECO-CHILE CRECE CONTIGO": "Arauco 983",
    "DIDECO-VIVIENDA": "Arauco 983",
    "DIDECO-HABITABILIDAD": "Arauco 983",
    "DIDECO-4 A 7": "Arauco 983",
    "DIDECO-JEFAS DE HOGAR": "Arauco 983",
    "DIDECO-VINCULOS": "Arauco 983",
    "DIDECO-ESTRATIFICACION SOCIAL": "Arauco 983",
    "DIDECO-OOCC": "Arauco 983",
    "DIDECO-COMUNICACIONES": "Arauco 983",
    "DIDECO-CENTRO DE LA MUJER": "Arauco 983",
    "DIDECO-MUJER SEXUALIDAD Y MATERNIDAD": "Arauco 983",
    "DIDECO-CASA DE ACOGIDA": "Arauco 983",
    "DIDECO-ASISTENCIA SOCIAL": "Arauco 983",
    "DIDECO-PROGRAMA CALLE": "Arauco 983",
    "DIDECO-PROGRAMA FAMILIAS": "Arauco 983",
    "DIDECO-EMPODERAMIENTO DESARROLLO INTEGRAL": "Arauco 983",
    "DIDECO-OMAJ": "Arauco 983",
    "DIDECO-SUBISDIOS ESTATALES Y PENSIONES": "Arauco 983",
    "DIDECO-SUBSIDIOS ESTATALES": "Arauco 983",
    "DIDECO- PREVENCIÓN DE LA VIOLENCIA": "Arauco 983",
    "DIDECO-ADULTO MAYOR": "Arauco 983",
    "DIDECO-CENTRO DIURNO": "Arauco 983",
    "DIDECO-RESIDENCIA TRANSITORIA": "Arauco 983",
    "DIDECO-SUBSIDIOS Y PENSIONES": "Arauco 983",
    "DIDECO-ORGANIZACIONES COMUNITARIAS": "Arauco 983",
    "DIDECO-CONTROL Y GESTION Y LOGISTICA": "Arauco 983",
    "DIDECO-REGISTRO SOCIAL DE HOGARES": "Arauco 983",
    "DIDECO-BECAS": "Arauco 983",
    "DIDECO-OFICINA DE LA DIVERSIDAD SOCIAL Y CULTURAL": "Arauco 983",
    "DIDECO-MUJERES JEFAS DE HOGAR": "Arauco 983",
    "DIDECO-MUJERES DERECHOS SEXUALES Y REPRODUCTIVOS": "Arauco 983",
    "PROGRAMA DE PREVENCION DE LA VIOLENCIA DE GENERO": "Arauco 983",
    "DIDECO-RED LOCAL DE APOYOS Y CIUDADANOS": "Arauco 983",
    "DIDECO-DISCAPACIDAD": "Arauco 983",
    "DIDECO-OMAR": "Arauco 983",
    "DIDECO-EMERGENCIAS SOCIALES": "Arauco 983",
    "DIDECO-CONSULTORIO JURIDICO": "Arauco 983",
    "DIDECO-DERECHO DE ASEO": "Arauco 983",
    "DIDECO-SERNAC": "Arauco 983",
    "DIDECO-BIENES NACIONALES MUNICIPAL": "Arauco 983",
    "DIDECO-PROGRAMA APOYO A LA SEGURIDAD ALIMENTARIA": "Arauco 983",
    "DIDECO-ASENTAMIENTOS PRECARIOS(CAMPAMENTOS)": "Arauco 983",
    "DIDECO-PROGRAMA DE ACOMPAÑAMIENTO INTEGRAL FAMILIAR": "Arauco 983",
    "DIDECO-OFICINA DE MEDIACION": "Arauco 983",
    "OBRAS": "Avenida Libertad 431, Interior",
    "OBRAS-DEPTO ELECTRICO": "Avenida Libertad 431, Interior",
    "OBRAS-EDIFICACIÓN": "Avenida Libertad 431, Interior",
    "OBRAS-VIAL": "Avenida Libertad 431, Interior",
    "OBRAS-VIAL ELECTRICOS": "Avenida Libertad 431, Interior",
    "OBRAS-SUBDIVISION Y LOTEO": "Avenida Libertad 431, Interior",
    "OBRAS-EJECUCION": "Avenida Libertad 431, Interior",
    "DIDEPRO": "Claudio Arrau 602",
    "DESARROLLO ECON. Y PRODUCTIVO": "Claudio Arrau 602",
    "OMIL": "Claudio Arrau 602",
    "DIDEPRO-OMIL": "Claudio Arrau 602",
    "DIDEPRO-PRODESAL": "Claudio Arrau 602",
    "DIDEPRO-COWORK": "Claudio Arrau 602",
    "ASEO": "Sepúlveda Labbé 109",
    "ASEO-ORNATO": "Sepúlveda Labbé 109",
    "ASEO-AREAS VERDES": "Sepúlveda Labbé 109",
    "ASEO-DIMENSION": "Sepúlveda Labbé 109",
    "ASEO-MEDIO AMBIENTE": "Sepúlveda Labbé 109",
    "ASEO-CENTRO VETERINARIO": "Sepúlveda Labbé 109",
    "ASEO-MEJORAMIENTO DE ESPACIOS PÚBLICOS": "Sepúlveda Labbé 109",
    "SEGURIDAD PUBLICA": "Pedro Aguirre Cerda 297",
    "SEGURIDAD PUBLICA - OPERADOR DE CAMARAS": "Pedro Aguirre Cerda 297",
    "SEGURIDAD PUBLICA-APARCADERO MUNICIPAL": "Pedro Aguirre Cerda 297",
    "INSPECCION": "Pedro Aguirre Cerda 297",
    "INSPECCION-JUSTICIA VECINAL": "Pedro Aguirre Cerda 297",
    "ADM-EMERGENCIA": "Pedro Aguirre Cerda 297",
    "SUREFI-ESTADIO": "Pedro Aguirre Cerda 297",
    "SECPLA": "Herminda Martín 563",
    "SECPLA - QUIERO MI BARRIO": "Herminda Martín 563",
    "SECPLA - PARTICIPACION CIUDADANA": "Herminda Martín 563",
    "CULTURA": "Herminda Martín 579",
    "CULTURA-CENTRO CULTURAL": "Herminda Martín 579",
    "CULTURA-BIBLIOTECA": "Arauco 974",
    "CULTURA-MUSEO ARRAU": "Claudio Arrau 558",
    "CULTURA-MUSEO CIENCIAS NATURALES": "Pedro Aguirre Cerda s/n",
    "CULTURA-ESCUELA ARTISTICA": "Arauco 356",
    "EDUCACION": "Rosas 530",
    "SALUD": "Herminda Martín 557",
    "SALUD-FINANZAS": "Herminda Martín 557",
    "TRANSITO": "Maipón 277",
    "TRANSITO-LICENCIAS": "Maipón 277",
    "1ER JPL": "Avenida Ecuador 317",
    "2DO JPL": "Avenida Ecuador 429",
    "DEPORTE Y RECREACION": "5 de Abril 535",
    "DEPORTES Y RECREACION": "5 de Abril 535",
    "TURISMO": "Dieciocho de Septiembre 510",
    "DIDECO-HOSPEDERIA": "Avenida O´Higgins 1290",
    "SEGURIDAD PUBLICA - 24 HRS": "Avenida Libertad 374",
    "DIDECO-OPD": "Gamero 318",
    "INSPECCION-SENDA": "Claudio Arrau 718",
    "SUREFI-CENTRO DEPORTIVO QUILAMAPU": "Paul Harris con Flores Millán",
    "CEMENTERIO": "Sepúlveda Bustos s/n",
    "ADM-MERCADO": "Arturo Prat 605",
    "DELEGACION QUINCHAMALI": "Camino a Quinchamalí s/n",
    "DELEGACIÓN ORIENTE": "Avenida Nueva Oriente con Alonso de Ercilla",
    "EXTERIOR": "Sin dirección fija",
}

# ── Paleta institucional ───────────────────────────────────────────────────────
C = {
    "rojo":              "#C8102E",
    "rojo_hover":        "#a00d23",
    "rojo_light":        "#fce8ec",
    "rojo_dark":         "#8b0a1f",
    "blanco":            "#ffffff",
    "gris_bg":           "#f0f2f7",
    "gris_borde":        "#dde3ec",
    "gris_sub":          "#6b7a99",
    "gris_placeholder":  "#a0aec0",
    "texto":             "#1a2035",
    "texto_claro":       "#4a5568",
    "verde":             "#16783a",
    "verde_light":       "#e8f5ee",
    "amarillo":          "#b45309",
    "amarillo_light":    "#fef3c7",
    "azul_acento":       "#2563eb",
    "sombra":            "#e2e8f0",
    "badge_bg":          "#eef2ff",
    "badge_fg":          "#3730a3",
    "label_claro":       "#6f8fb3",
    "gris_panel":        "#f9fafb",
    "dropdown_sel":      "#fff0f3",
    "dropdown_sel_fg":   "#C8102E",
    "dropdown_hover":    "#f5f7ff",
    "gris_readonly":     "#f8f9fb",
    "rojo_estado":       "#C8102E",
    }